services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  #frontend:
  #  build: ./apps/frontend
  #  ports:
  #    - "3000:80"
  #  depends_on:
  #    - backend

  #ranker:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.ranker
  #  ports:
  #    - "5000:5000"
  #  depends_on:
  #    - db

  db:
    image: mariadb:12.1.2
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: polar
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mariadb-data:
